blender_render_mask_path: /home/andrea/Desktop/Thesis_project/blender_render/obj_000010.ply/masks
blender_render_path: /home/andrea/Desktop/Thesis_project/blender_render/obj_000010.ply
cam2Pos_path: /home/andrea/Desktop/Thesis_project/config/obj_000010_cam2Pos.yaml
glb_path: /home/andrea/Desktop/Thesis_project/Models/banana_000019_sample.glb
image_path: /home/andrea/Desktop/Thesis_project/Inputs/000019.jpg
mask_path: /home/andrea/Desktop/Thesis_project/Segmented/mask
model_path: /home/andrea/Desktop/Thesis_project/Models/
ply_path: /home/andrea/Desktop/Thesis_project/Models/banana_000019_sample.ply
scale_path: /home/andrea/Desktop/Thesis_project/config/obj_000010_scale.yaml
segmentation_path: /home/andrea/Desktop/Thesis_project/Segmented/rgb
text_prompt: banana
